---
applications:
  pezdispenser:
    deployments:
      - name: development
        url: api.run.core.pez.pivotal.io --skip-ssl-validation
        org: sys-pez
        space: pez-dev 
        path: pezdispenser/development.yml
        push_cmd: push-zdd dispenserdev 
      - name: production
        url: api.run.core.pez.pivotal.io --skip-ssl-validation
        org: sys-pez
        space: pez
        path: pezdispenser/production.yml
        push_cmd: push-zdd dispenser 

